### ISSUE TITLE
Side menu overlapping content

### ISSUE THREAD

**Issue by machisuji** [simerplaha/def.io#1]
See

![image](https://user-images.githubusercontent.com/158871/46529758-8ad69f80-c88f-11e8-91d7-1e97e82988ad.png)

Using Chrome (Version 69.0.3497.81 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)).

**Comment by simerplaha** [comment]
This should be fixed now. Can you please confirm ? You will probably need to clear browser cache to fetch the new static files.

**Comment by machisuji** [comment]
All good now, thanks! :+1:

**Comment by simerplaha** [comment]
Thanks for letting me know. Appreciate it :)
